### ISSUE TITLE
License checklist

### ISSUE THREAD

**Issue by Tammy1128** [UBC-MDS/stockAnalyzer#60]

**Comment by ZIBOWANGKANGYU** [comment]
Some thoughts about choosing the right license:
I read the article here and think it is easy to understand for people without a legal background like us:
Essentially, people use licenses for their code because they are afraid of being sued. In addition, the use of the three licenses also mitigate different worries people might have:
(1) The MIT license is if you’re afraid no one will use your code;
(2) The Apache license is if you are also afraid of legal ambiguity and patent trolls;
(3) The GNU GPL licenses are if you are afraid of someone else profiting from your work.

I believe we should use MIT license, for the following reasons:
(1) We are at the beginning of our data science careers. Therefore, we want more people to use our software. From this perspective, an MIT license would be preferable. 
(2) Our software is a bit simple and probably not worthy of patent yet. Therefore, I do not see a need to use the Apache license.
(3) It would be great in fact if somebody profits from our work, which shows the value of our work and can be an addition to our resume. Also, we probably do not really care about whether the final product of other people using our work is open source or not.

**Comment by Tammy1128** [comment]
Yes, I agreed with your ideas. I think we can continue to use the MIT license on our GitHub repository, however, we need to change the name under the MIT license from group 20 DSCI 524 to our members specific names to satisfy transparency and make more sense. 

Moreover, from this [choosealicense](https://choosealicense.com/licenses/) website, it provides different licenses to the public and for the MIT:

> "A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code."

Reference: Licenses. (n.d.). Retrieved March 19, 2021, from https://choosealicense.com/licenses/

**Comment by ZIBOWANGKANGYU** [comment]
Agreed! And in fact, people will likely open-source their work even if we have an MIT license. This is because if they use our work, and we continue to update our case after the course, it is more convenient for users to open source, instead of using a fork from this repository, which does not synchronize our improved work automatically. Therefore, we should not worry too much about other people not open-sourcing our work here. 
https://exygy.com/blog/which-license-should-i-use-mit-vs-apache-vs-gpl/

**Comment by MarcSunUBC** [comment]
Thank you Mark for sharing your thoughts, you have very legitimate reason to choose MIT license, which is very suitable to our little project. The teammates are willing to make this package free and open to public. We also encourage people who are interest in our package to become part of the team for future improvement.

**Comment by williamxu7** [comment]
Me too, I agree. MIT is a great idea in my opinion. I think we are open to the idea that people can use our package freely and we are happy to receive feedback. MIT license is also short and simple, which also fit our needs. In the future, we may plan to improve our package when we obtain more data science and investment knowledge. Using MIT license would also provide us more flexibility in case we would want future improvement.
Tammy has a good point, we would have members' specific names in the license file for both projects.
